### ISSUE TITLE
To Do App Review

### ISSUE THREAD

**Issue by julzedz** [MahdiSohaily/Todo-app#6]
Hello @MahdiSohaily ,👋🏾
having carefully reviewed your code, we found it excellent and well-organized.
Several highlights include: 🎯

 - No Linters error.
 - Good usage of HTML semantic elements.
 - Good git flow control.

Here are a few tips to improve your code even:
1. Adding a button to the Task on the mobile version will be more intuitive and user friendly. 

Cheers and happy coding! 😎

**Comment by MahdiRezaeiDev** [comment]
Thanks, dear @julzedz for your helpful feedback.
I will consider that.
